/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    navigation: Navigation;
    redirects: Redirect;
    'course-landing': CourseLanding;
    'exam-categories': ExamCategory;
    faculty: Faculty;
    'hero-carousel': HeroCarousel;
    testimonials: Testimonial;
    videos: Video;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'course-landing': CourseLandingSelect<false> | CourseLandingSelect<true>;
    'exam-categories': ExamCategoriesSelect<false> | ExamCategoriesSelect<true>;
    faculty: FacultySelect<false> | FacultySelect<true>;
    'hero-carousel': HeroCarouselSelect<false> | HeroCarouselSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ta' | 'kn') | ('en' | 'ta' | 'kn')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'ta' | 'kn';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Display order. Drag rows in the list view to reorder.
   */
  order?: number | null;
  /**
   * Uncheck to hide this item from the public site.
   */
  active?: boolean | null;
  /**
   * Set when the item is soft-deleted. Empty means active.
   */
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  /**
   * Human-friendly name for this asset in the admin (e.g. 'Hero — Aisha desktop').
   */
  name?: string | null;
  /**
   * Meaningful alt text. Use an empty string only for decorative images.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Display order. Drag rows in the list view to reorder.
   */
  order?: number | null;
  /**
   * Uncheck to hide this item from the public site.
   */
  active?: boolean | null;
  /**
   * Set when the item is soft-deleted. Empty means active.
   */
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  title: string;
  /**
   * URL segment, e.g. 'about'. Lowercase, hyphenated.
   */
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    /**
     * Per-locale <title>. Falls back to the page title if empty.
     */
    title?: string | null;
    /**
     * Meta description for this locale.
     */
    description?: string | null;
    /**
     * Optional canonical override. Defaults to the page's own URL.
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph / Twitter card image.
     */
    ogImage?: (number | null) | Media;
    /**
     * Exclude this page from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Display order. Drag rows in the list view to reorder.
   */
  order?: number | null;
  /**
   * Uncheck to hide this item from the public site.
   */
  active?: boolean | null;
  /**
   * Set when the item is soft-deleted. Empty means active.
   */
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  title: string;
  slug: string;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Public byline. Faculty profile, not the CMS editor account.
   */
  author?: (number | null) | Faculty;
  /**
   * Category pill shown on the blog card.
   */
  category?: (number | null) | ExamCategory;
  /**
   * Display read time, e.g. '6 min read'.
   */
  readTime?: string | null;
  coverImage?: (number | null) | Media;
  publishedAt?: string | null;
  seo?: {
    /**
     * Per-locale <title>. Falls back to the page title if empty.
     */
    title?: string | null;
    /**
     * Meta description for this locale.
     */
    description?: string | null;
    /**
     * Optional canonical override. Defaults to the page's own URL.
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph / Twitter card image.
     */
    ogImage?: (number | null) | Media;
    /**
     * Exclude this page from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faculty".
 */
export interface Faculty {
  id: number;
  /**
   * Display order. Drag rows in the list view to reorder.
   */
  order?: number | null;
  /**
   * Uncheck to hide this item from the public site.
   */
  active?: boolean | null;
  /**
   * Set when the item is soft-deleted. Empty means active.
   */
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  /**
   * e.g. 'Dr. Divya Mehta', 'CA Vikram Goyal'.
   */
  name: string;
  /**
   * Subject / discipline, e.g. 'Physics', 'Accountancy'.
   */
  role?: string | null;
  /**
   * Short credential line, e.g. 'AIIMS · 11 yrs teaching'.
   */
  credential?: string | null;
  photo?: (number | null) | Media;
  /**
   * Avatar/accent hex used when no photo is set, e.g. '#1F8A5B'.
   */
  accentColor?: string | null;
  /**
   * Longer profile body shown on the Faculty page.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exam-categories".
 */
export interface ExamCategory {
  id: number;
  /**
   * Display order. Drag rows in the list view to reorder.
   */
  order?: number | null;
  /**
   * Uncheck to hide this item from the public site.
   */
  active?: boolean | null;
  /**
   * Set when the item is soft-deleted. Empty means active.
   */
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  /**
   * Display name, e.g. 'NEET', 'JEE Main', 'CA Foundation'.
   */
  name: string;
  /**
   * URL/tab key, e.g. 'neet'. Lowercase, hyphenated.
   */
  slug: string;
  /**
   * Coarse grouping for the Courses tab filter.
   */
  group?: ('neet' | 'jee' | 'commerce' | 'other') | null;
  /**
   * Display-only count shown on the chip, e.g. '2.1k batches'.
   */
  batchCount?: string | null;
  /**
   * Optional hex accent for the chip/icon, e.g. '#2C4BFF'.
   */
  accentColor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Display order. Drag rows in the list view to reorder.
   */
  order?: number | null;
  /**
   * Uncheck to hide this item from the public site.
   */
  active?: boolean | null;
  /**
   * Set when the item is soft-deleted. Empty means active.
   */
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  /**
   * Where this menu renders.
   */
  location: 'header' | 'footer';
  items?:
    | {
        /**
         * Footer column heading this link sits under (e.g. 'Company', 'Learn', 'Support'). Items sharing a column render together. Leave empty for header menus.
         */
        column?: string | null;
        label: string;
        /**
         * Relative path (e.g. /about) or absolute URL.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Display order. Drag rows in the list view to reorder.
   */
  order?: number | null;
  /**
   * Uncheck to hide this item from the public site.
   */
  active?: boolean | null;
  /**
   * Set when the item is soft-deleted. Empty means active.
   */
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  /**
   * Source path, e.g. /old-url.
   */
  from: string;
  /**
   * Destination path or URL.
   */
  to: string;
  type?: ('301' | '302') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-landing".
 */
export interface CourseLanding {
  id: number;
  /**
   * Display order. Drag rows in the list view to reorder.
   */
  order?: number | null;
  /**
   * Uncheck to hide this item from the public site.
   */
  active?: boolean | null;
  /**
   * Set when the item is soft-deleted. Empty means active.
   */
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  title: string;
  slug: string;
  /**
   * Drives the Courses tab filter and the card tag.
   */
  exam?: (number | null) | ExamCategory;
  /**
   * Lead educator shown on the card.
   */
  faculty?: (number | null) | Faculty;
  /**
   * Card eyebrow tag, e.g. 'NEET · Biology'.
   */
  tag?: string | null;
  /**
   * Display rating, e.g. 4.9. Marketing display only.
   */
  rating?: number | null;
  /**
   * Short marketing teaser. Not the real course description.
   */
  teaser?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Optional marketing display price, e.g. '₹24,999'. NOT authoritative pricing (LMS owns that).
   */
  priceLabel?: string | null;
  /**
   * Optional struck-through 'was' price, e.g. '₹38,000'.
   */
  wasLabel?: string | null;
  /**
   * Card stats, e.g. Duration / Live classes / Mock tests.
   */
  meta?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional hex for the card's top border, e.g. '#2C4BFF'.
   */
  accentColor?: string | null;
  /**
   * Outbound deep link into the LMS app (Enroll/View). HTTP only.
   */
  lmsUrl?: string | null;
  seo?: {
    /**
     * Per-locale <title>. Falls back to the page title if empty.
     */
    title?: string | null;
    /**
     * Meta description for this locale.
     */
    description?: string | null;
    /**
     * Optional canonical override. Defaults to the page's own URL.
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph / Twitter card image.
     */
    ogImage?: (number | null) | Media;
    /**
     * Exclude this page from search engines and the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-carousel".
 */
export interface HeroCarousel {
  id: number;
  /**
   * Display order. Drag rows in the list view to reorder.
   */
  order?: number | null;
  /**
   * Uncheck to hide this item from the public site.
   */
  active?: boolean | null;
  /**
   * Set when the item is soft-deleted. Empty means active.
   */
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  /**
   * Desktop/wide image (e.g. 16:9). Shown from the md breakpoint up.
   */
  image: number | Media;
  /**
   * Optional portrait crop for small screens (e.g. 4:5). Falls back to the desktop image when empty.
   */
  mobileImage?: (number | null) | Media;
  studentName: string;
  /**
   * Result/achievement headline shown on the slide.
   */
  achievement?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Display order. Drag rows in the list view to reorder.
   */
  order?: number | null;
  /**
   * Uncheck to hide this item from the public site.
   */
  active?: boolean | null;
  /**
   * Set when the item is soft-deleted. Empty means active.
   */
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  studentName: string;
  photo?: (number | null) | Media;
  quote: string;
  /**
   * Course or context for this testimonial.
   */
  course?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  /**
   * Display order. Drag rows in the list view to reorder.
   */
  order?: number | null;
  /**
   * Uncheck to hide this item from the public site.
   */
  active?: boolean | null;
  /**
   * Set when the item is soft-deleted. Empty means active.
   */
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  title: string;
  /**
   * YouTube video ID (the part after watch?v=).
   */
  youtubeId: string;
  /**
   * Optional custom thumbnail for the lite facade.
   */
  thumbnail?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'course-landing';
        value: number | CourseLanding;
      } | null)
    | ({
        relationTo: 'exam-categories';
        value: number | ExamCategory;
      } | null)
    | ({
        relationTo: 'faculty';
        value: number | Faculty;
      } | null)
    | ({
        relationTo: 'hero-carousel';
        value: number | HeroCarousel;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  order?: T;
  active?: T;
  deletedAt?: T;
  deletedBy?: T;
  name?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  order?: T;
  active?: T;
  deletedAt?: T;
  deletedBy?: T;
  title?: T;
  slug?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  order?: T;
  active?: T;
  deletedAt?: T;
  deletedBy?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  author?: T;
  category?: T;
  readTime?: T;
  coverImage?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  order?: T;
  active?: T;
  deletedAt?: T;
  deletedBy?: T;
  location?: T;
  items?:
    | T
    | {
        column?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  order?: T;
  active?: T;
  deletedAt?: T;
  deletedBy?: T;
  from?: T;
  to?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-landing_select".
 */
export interface CourseLandingSelect<T extends boolean = true> {
  order?: T;
  active?: T;
  deletedAt?: T;
  deletedBy?: T;
  title?: T;
  slug?: T;
  exam?: T;
  faculty?: T;
  tag?: T;
  rating?: T;
  teaser?: T;
  heroImage?: T;
  priceLabel?: T;
  wasLabel?: T;
  meta?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  accentColor?: T;
  lmsUrl?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalUrl?: T;
        ogImage?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exam-categories_select".
 */
export interface ExamCategoriesSelect<T extends boolean = true> {
  order?: T;
  active?: T;
  deletedAt?: T;
  deletedBy?: T;
  name?: T;
  slug?: T;
  group?: T;
  batchCount?: T;
  accentColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faculty_select".
 */
export interface FacultySelect<T extends boolean = true> {
  order?: T;
  active?: T;
  deletedAt?: T;
  deletedBy?: T;
  name?: T;
  role?: T;
  credential?: T;
  photo?: T;
  accentColor?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-carousel_select".
 */
export interface HeroCarouselSelect<T extends boolean = true> {
  order?: T;
  active?: T;
  deletedAt?: T;
  deletedBy?: T;
  image?: T;
  mobileImage?: T;
  studentName?: T;
  achievement?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  order?: T;
  active?: T;
  deletedAt?: T;
  deletedBy?: T;
  studentName?: T;
  photo?: T;
  quote?: T;
  course?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  order?: T;
  active?: T;
  deletedAt?: T;
  deletedBy?: T;
  title?: T;
  youtubeId?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  hero?: {
    /**
     * Pill above the headline, e.g. 'Trusted by 10,000+ rankers'.
     */
    badge?: string | null;
    /**
     * Main headline. Wrap the accent word in the 'accentWord' field.
     */
    headline?: string | null;
    /**
     * Italic cobalt word appended to the headline, e.g. 'topper.'.
     */
    accentWord?: string | null;
    subCopy?: string | null;
  };
  trust?: {
    /**
     * e.g. '4.9'.
     */
    rating?: string | null;
    /**
     * e.g. '12,400+ student reviews'.
     */
    reviewCount?: string | null;
  };
  /**
   * The stat feature cards in the 'Why' section.
   */
  whyStats?:
    | {
        /**
         * e.g. '10,000+'.
         */
        stat?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    heading?: string | null;
    /**
     * Italic cobalt word in the CTA heading, e.g. 'waiting.'.
     */
    accentWord?: string | null;
    body?: string | null;
    /**
     * Fine print under the form.
     */
    note?: string | null;
  };
  /**
   * Footer social URLs. Leave empty to hide an icon.
   */
  social?: {
    instagram?: string | null;
    youtube?: string | null;
    x?: string | null;
    telegram?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        headline?: T;
        accentWord?: T;
        subCopy?: T;
      };
  trust?:
    | T
    | {
        rating?: T;
        reviewCount?: T;
      };
  whyStats?:
    | T
    | {
        stat?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        accentWord?: T;
        body?: T;
        note?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        youtube?: T;
        x?: T;
        telegram?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}